### PR TITLE
Param mapping fix

### PR DESCRIPTION
**Pull request by ivargrimstad**
Added a crude solution for mapping violations to parameter names.

### CODE REVIEW

**Comment by chkal** [comment]
Awesome! Thanks a lot. I think this should work fine. :)

**Comment by ivargrimstad** [comment]
Cool!
I have an example using it here: 

https://github.com/ivargrimstad/mvc-samples/tree/master/post-redirect-get

**Comment by chkal** [comment]
Great. I'll have a look at your example later today.

The showcase app should also now highlight invalid inputs correctly:

https://github.com/chkal/mvc-toolbox/tree/master/showcase/

BTW: The snapshots are automatically deployed to the Sonatype OSS Snapshot Repository, so an updated version should available right now.

**Comment by chkal** [comment]
Unfortunately this solution doesn't seem to work correctly if the annotated field/parameter name is different from the submitted form parameter name.

``` java
public class MyForm {

  @FormParam("firstname")
  @Length(min = 5)
  private String someField;

}
```

In this case the code would create a message with the param property set to `someField` instead of `firstname`. Too bad the param isn't available in the ConstraintViolation like it is the case for BindingError.

**Comment by ivargrimstad** [comment]
Yes, you're right. I will see if I can find time to have a look at it and see what we can do...

Ivar

**Pull request merged**
