### PR TITLE
Constraint mapping

### PR DESCRIPTION
**Pull request by ivargrimstad**
Using reflection to do the mapping. Ugly, but seem to work :)

### CODE REVIEW

**Comment by chkal** [comment]
Yeah, that could work. But this only works for fields, not for controller method params, correct?

My first attempt was to do something like this:

``` java
ConstraintViolation<?> violation = ...
String param = null;

for (String p : request.getParameterMap().keySet()) {
  Set<ConstraintViolation<?>> violations = bindingResult.getViolations(p);
  if (violations.contains(violation)) {
    param = p;
  }
}
```

Unfortunately it is not so easy to get a list of "all request parameters". It looks like `HttpServletRequest#getParameterMap()` won't work here because JAX-RS consumes the body content of the request.

I'm wondering whether this should be fixed on the spec level. It's weird that there is no way to check which parameter caused a ConstraintViolation.

Perhaps `BindingResult` should not return `ConstraintViolations` directly but something like this:

``` java
public interface ValidationError { 
  String getParam();
  ConstraintViolation<?> getViolation();
}
```

Wouldn't this make sense? The `BindingError` interface also provides `getParam()` which makes it very easy to use.

**Comment by ivargrimstad** [comment]
Controller method params is a problem, yes. They get the name arg0, arg1,... etc. no matter what the @FormParam annotation says.

I think your suggestion of providing a getParam() method to the ValidationError in the same manner as the BindingError case makes a lot of sense. This would need to be set in the Binding Interceptor in Ozark then?

**Comment by chkal** [comment]
Yes, I think this has to be handled in the `BindingInterceptor`. Not sure how. But `BindingResult` will need the parameter names for `ConstraintViolations` anyway to implement `BindingResult#getVioliation(pram)`. I see no reason why we shouldn't expose this information to the user in some way.

I'll prepare a proposal for the EG list.

**Comment by chkal** [comment]
I'm merging you pull request as it is the best code we have so far. However, I would really like to see the MVC API to improve here.

**Comment by chkal** [comment]
I proposed the idea of adding a `ValidationError` interface on the EG list:

https://java.net/projects/mvc-spec/lists/jsr371-experts/archive/2016-02/message/0

**Comment by ivargrimstad** [comment]
Excellent!

**Pull request merged**
